CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    registration_date DATE,
    PRIMARY KEY (id),
    CONSTRAINT unique_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    user_id BIGINT,
    url TEXT,
    description TEXT,
    created_time TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS tags (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    item_id BIGINT,
    name VARCHAR(255),
    PRIMARY KEY (id),
    FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT unique_name UNIQUE (name)
);


DELETE FROM tags;
DELETE FROM items;
DELETE FROM users;

ALTER TABLE tags ALTER COLUMN id RESTART WITH 1;
ALTER TABLE items ALTER COLUMN id RESTART WITH 1;
ALTER TABLE users ALTER COLUMN id RESTART WITH 1;


-- DROP TABLE tags;
-- DROP TABLE items;
-- DROP TABLE users;